language: java
git:
  submodules: true
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ant ant-optional python-virtualenv python-pip
install: mvn install -DskipTests -Ptravis
script: mvn test -Ptravis
