language: java
git:
  submodules: true
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ant ant-optional python-virtualenv python-pip
install: travis_retry mvn install -DskipTests
script: mvn install -P-all,travis
