# non geOrchestra images
database:
  image: georchestra/database
  environment:
    - POSTGRES_USER=georchestra
    - POSTGRES_PASSWORD=georchestra
  volumes:
    - postgresql_data:/var/lib/postgresql/data

ldap:
  image: georchestra/ldap
  environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD=secret
      - SLAPD_ADDITIONAL_MODULES=memberof,groupofmembers
  volumes:
    - ldap_data:/var/lib/ldap
    - ldap_config:/etc/ldap

smtp:
  image: camptocamp/smtp-sink

courier-imap:
  image: camptocamp/courier-imap
  volumes_from:
    - smtp:rw

webmail:
  image: camptocamp/sqwebmail
  ports:
    - "8081:80"
  volumes_from:
    - smtp:rw

geoserver_geodata:
  image: georchestra/ssh_data
  ports:
    - "2222:22"
  volumes:
    - geoserver_geodata:/home/geoserver/data

# geOrchestra images
    
geoserver:
  image: georchestra/geoserver:15.12
  volumes:
    - geoserver_datadir:/var/local/geoserver
    - geoserver_geodata:/var/local/geodata
    - geoserver_tiles:/var/local/tiles
  links:
    - database
    - ldap

geowebcache:
  image: georchestra/geowebcache:15.12
  volumes:
    - geowebcache_tiles:/var/local/tiles

proxy:
  image: georchestra/security-proxy:15.12
  ports:
    - "8080:8080"
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - extractorapp
    - ldapadmin
    - geonetwork
    - header
    - geoserver
    - analytics
    - catalogapp
    - downloadform

cas:
  image: georchestra/cas:15.12
  links:
    - ldap

mapfishapp:
  image: georchestra/mapfishapp:15.12
  volumes:
    - mapfishapp_uploads:/var/local/uploads
  links:
    - database
  volumes:
    - mapfishapp_uploads:/var/local/uploads

extractorapp:
  image: georchestra/extractorapp:15.12
  volumes:
    - extractorapp_extracts:/var/local/extracts
  links:
    - database
    - smtp
  volumes:
    - extractorapp_extracts:/var/local/extracts


header:
  image: georchestra/header:15.12

ldapadmin:
  image: georchestra/ldapadmin:15.12
  links:
    - database
    - ldap
    - smtp

geonetwork:
  image: georchestra/geonetwork:15.12
  ports:
    - "1099:1099"
  links:
    - database
    - ldap
  volumes:
    - geonetwork_datadir:/var/local/geonetwork

analytics:
  image: georchestra/analytics:15.12
  links:
    - database

catalogapp:
  image: georchestra/catalogapp:15.12

downloadform:
  image: georchestra/downloadform:15.12
