# non geOrchestra images
database:
  image: georchestra/database
  environment:
    - POSTGRES_USER=georchestra
    - POSTGRES_PASSWORD=georchestra
  volumes:
    - postgresql_data:/var/lib/postgresql/data

ldap:
  image: georchestra/ldap
#  volumes:
#    - ldap_data:/var/lib/ldap

smtp-sink:
  build: ./docker/smtp/smtp-sink

courier-imap:
  build: ./docker/smtp/courier-imap
  volumes_from:
    - smtp-sink:rw

webmail:
  build: ./docker/smtp/webmail
  ports:
    - "8081:80"
  volumes_from:
    - smtp-sink:rw

geoserver_geodata:
  image: georchestra/ssh_data
  ports:
    - "2222:22"
  volumes:
    - geoserver_geodata:/home/geoserver/data

# geOrchestra images
    
geoserver:
  image: georchestra/geoserver
  volumes:
    - geoserver_datadir:/var/local/geoserver
    - geoserver_geodata:/var/local/geodata
    
proxy:
  image: georchestra/security-proxy
  ports:
    - "8080:8080"
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - extractorapp
    - ldapadmin
    - geonetwork
    - header
    - geoserver
  volumes:
    - ./docker/datadir:/etc/georchestra

cas:
  image: georchestra/cas
  links:
    - ldap
  volumes:
    - ./docker/datadir:/etc/georchestra

mapfishapp:
  image: georchestra/mapfishapp
  links:
    - database
  volumes:
    - ./docker/datadir:/etc/georchestra

extractorapp:
  image: georchestra/extractorapp
  links:
    - database
    - smtp-sink
  volumes:
    - ./docker/datadir:/etc/georchestra

header:
  image: georchestra/header
  volumes:
    - ./docker/datadir:/etc/georchestra

ldapadmin:
  image: georchestra/ldapadmin
  links:
    - database
    - ldap
    - smtp-sink
  volumes:
    - ./docker/datadir:/etc/georchestra

geonetwork:
  image: georchestra/geonetwork
  ports:
    - "1099:1099"
  links:
    - database
    - ldap
  volumes:
    - ./docker/datadir:/etc/georchestra
